# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=30)),
                ('detail', models.TextField(max_length=300)),
                ('detail_more', models.TextField(max_length=300)),
                ('group', models.CharField(max_length=30)),
                ('contact', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ('group',),
            },
        ),
    ]
