# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_content', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('brief_image_url', models.CharField(max_length=30)),
                ('edit_person', models.CharField(max_length=30)),
                ('edit_time', models.DateField()),
                ('category', models.CharField(choices=[('0', '\u5934\u6761\u65b0\u95fb'), ('1', '\u7126\u70b9\u5173\u6ce8'), ('2', '\u6559\u5b66\u65b0\u95fb')], max_length=1)),
            ],
        ),
    ]
