# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171030_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='brief_image_url',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
