# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171030_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='brief_image_url',
            field=models.CharField(default='null', max_length=60, null=True),
        ),
    ]
