# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171030_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='importance',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_time',
            field=models.DateField(default=datetime.date(2017, 10, 30)),
        ),
    ]
