# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171030_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='PV',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
    ]
