# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20171030_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ph',
            field=models.ImageField(null=True, upload_to='uploadImages', verbose_name='\u56fe\u7247'),
        ),
    ]
