# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20171106_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='brief_content',
            field=models.CharField(max_length=600),
        ),
    ]
