# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 13:55
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20171106_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='brief_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
