# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_image_img_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='uploadImages/', verbose_name='File'),
        ),
    ]
