# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20171108_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('0', '\u5934\u6761\u65b0\u95fb'), ('1', '\u7126\u70b9\u5173\u6ce8'), ('2', '\u6559\u5b66\u65b0\u95fb'), ('101', '\u9662\u7cfb\u8bbe\u7f6e')], max_length=4),
        ),
        migrations.AlterField(
            model_name='news',
            name='ph',
            field=models.ImageField(blank=True, null=True, upload_to='uploadImages', verbose_name='\u56fe\u7247'),
        ),
    ]
